name: clean_arch_weather
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#NETWORK
  retrofit: ^3.0.1+1
  json_annotation: any
  dio: ^4.0.4

#LOGIC
  flutter_hooks: ^0.18.2+1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

#DESIGN
  bottom_navy_bar: ^6.0.0
  hexcolor: ^2.0.6  
  fl_chart: ^0.41.0
  radar_chart: ^2.1.0
  flutter_glow: ^0.2.0
  simple_gradient_text: ^1.2.2
  flutter_spinkit: ^5.1.0
  flutter_switch: ^0.3.2

#HOME WIDGET
  home_widget: ^0.1.5

#MATH
  equatable: ^2.0.3
  intl: ^0.17.0

#GPS
  location: ^4.3.0

#OTHER
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
 #NETWORK 
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.7
  json_serializable: '>4.4.0'


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/cloud/
    - assets/images/lighting/
    - assets/images/moon/
    - assets/images/rain/
    - assets/images/snow/
    - assets/images/star/
    - assets/images/sun/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

